var n,nome;
n="Adalberto";
n="Belarmina";
n="Astrogildo";
n="Pafuncia";
//document.write(n);
nome=["Adalberto","Belarmina","Astrogildo","Pafuncia"];
//document.write(nome);
document.getElementById("dv1").innerHTML=n;
document.querySelector(".teste").innerHTML=nome;
document.querySelector("h2").innerHTML=n;